export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string
          name: string
          email: string
          phone?: string
          hotel_name: string
          hotel_address?: string
          hotel_city?: string
          hotel_state?: string
          hotel_country?: string
          hotel_website?: string
          rooms_count: number
          plan_id?: string
          subscription_status: string
          trial_ends_at?: string
          subscription_starts_at?: string
          subscription_ends_at?: string
          last_payment_at?: string
          next_payment_at?: string
          monthly_revenue: number
          total_reservations: number
          status: string
          notes?: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string
          hotel_name: string
          hotel_address?: string
          hotel_city?: string
          hotel_state?: string
          hotel_country?: string
          hotel_website?: string
          rooms_count: number
          plan_id?: string
          subscription_status: string
          trial_ends_at?: string
          subscription_starts_at?: string
          subscription_ends_at?: string
          last_payment_at?: string
          next_payment_at?: string
          monthly_revenue: number
          total_reservations: number
          status: string
          notes?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string
          hotel_name?: string
          hotel_address?: string
          hotel_city?: string
          hotel_state?: string
          hotel_country?: string
          hotel_website?: string
          rooms_count?: number
          plan_id?: string
          subscription_status?: string
          trial_ends_at?: string
          subscription_starts_at?: string
          subscription_ends_at?: string
          last_payment_at?: string
          next_payment_at?: string
          monthly_revenue?: number
          total_reservations?: number
          status?: string
          notes?: string
          created_at?: string
          updated_at?: string
        }
      }
      subscription_plans: {
        Row: {
          id: string
          name: string
          slug?: string
          description?: string
          price_monthly: number
          price_yearly?: number
          features?: string[]
          limits?: Json
          is_active: boolean
          is_featured?: boolean
          sort_order?: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug?: string
          description?: string
          price_monthly: number
          price_yearly?: number
          features?: string[]
          limits?: Json
          is_active: boolean
          is_featured?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string
          price_monthly?: number
          price_yearly?: number
          features?: string[]
          limits?: Json
          is_active?: boolean
          is_featured?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          client_id: string
          subscription_id?: string
          amount: number
          currency: string
          status: string
          payment_method?: string
          payment_provider?: string
          external_payment_id?: string
          invoice_url?: string
          receipt_url?: string
          paid_at?: string
          failed_at?: string
          refunded_at?: string
          failure_reason?: string
          metadata?: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          subscription_id?: string
          amount: number
          currency: string
          status: string
          payment_method?: string
          payment_provider?: string
          external_payment_id?: string
          invoice_url?: string
          receipt_url?: string
          paid_at?: string
          failed_at?: string
          refunded_at?: string
          failure_reason?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          subscription_id?: string
          amount?: number
          currency?: string
          status?: string
          payment_method?: string
          payment_provider?: string
          external_payment_id?: string
          invoice_url?: string
          receipt_url?: string
          paid_at?: string
          failed_at?: string
          refunded_at?: string
          failure_reason?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      support_tickets: {
        Row: {
          id: string
          client_id?: string
          title: string
          description: string
          priority: string
          status: string
          category?: string
          assigned_to?: string
          client_email?: string
          client_name?: string
          resolution?: string
          resolved_at?: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id?: string
          title: string
          description: string
          priority: string
          status: string
          category?: string
          assigned_to?: string
          client_email?: string
          client_name?: string
          resolution?: string
          resolved_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          title?: string
          description?: string
          priority?: string
          status?: string
          category?: string
          assigned_to?: string
          client_email?: string
          client_name?: string
          resolution?: string
          resolved_at?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}
